name: CI

on:
  push:
    branches: [ master, next ]
  pull_request:
    branches: [ master, next ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: |
       sudo apt install build-essential cmake

    - name: Build
      run: |
        cmake .
        make

    - name: Test
      run: |
        export GTEST_OUTPUT=xml
        make test
